apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apis
spec:
  replicas: 4
  selector:
    matchLabels:
      type: api
  template:
    metadata:
      labels:
        type: api
    spec:
      containers:
        - name: api
          image: registry.cluster.wik.cloud/public/echo
          ports:
            - containerPort: 8080
